### ISSUE TITLE
Really Robust Electrical Tape make gloves so robust they delete itself from the universe

### ISSUE THREAD

**Issue by ADepressedPyroshark** [WaspStation/WaspStation-1.0#504]
Issue reported from  Round ID: [1695](https://scrubby.melonmesa.com/round/1695) (BoomerStation - MRP)

Reporting client version: 513.1528

With some help from an admin I got Electrical Tape and applied to budget insuls and they vanished. Not even like "the sprite is fucked so its invisible" I mean it LITERALLY gets destroyed. I tried some other gloves and they vanished too. I haven't tried actual insuls. Other stuff works fine I think.
@AsciiSquid

**Comment by ADepressedPyroshark** [comment]
And as soon as I post, another bug pops up. Taping someones mouth shut doesn't give you it back if it fails. This could have just been because I had one left but still.

**Comment by AsciiSquid** [comment]
This is intentional, to a degree.

Tape insuls have a random chance of breaking after each use (50% prob with 3 grace uses before destruction). And tape muzzles are supposed to destroy themselves after removal since applying the same strip of tape over and over.

Will add some messages for clarity along with fixing the issues mentioned in #490 itself.
