### ISSUE TITLE
whitesand atmos is fucky

### ISSUE THREAD

**Issue by TheNeoGamer42** [WaspStation/WaspStation-1.0#686]
Issue reported from  Round ID: 2257 (White Sands - RP)

Reporting client version: 513.1532

When you have an area open to the outside while on whitesands, say, by having the door of the mining shuttle open, all the air leaves and its a complete vacuum instead of actually having the air of whitesands

**Comment by Maldaris** [comment]
![image](https://user-images.githubusercontent.com/1953773/104111635-3a421e00-52b2-11eb-8b2d-af69da960623.png)
So it turns out, Monstermos thinks that all atmos gasmixes that are marked as immutable, are also space, and should explosively decompress. Thanks Monster.

Will be pushing a fix for this shortly.

**Comment by Superyodeler** [comment]
Monster moment

**Comment by Maldaris** [comment]
Fixed by https://github.com/WaspStation/extools/pull/4/files

**Comment by Maldaris** [comment]
Fixed in #679
